spring:
  application:
    name: connets_app
  h2:
    console:
      enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-54-83-50-174.compute-1.amazonaws.com:5432/db1l075j0f3ocn
    username: 5432
    password: 9f4ff93fe2a4d294f26103cac17f0b6fb8d89cd699bc05bd983ff84159ab202d
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8083
check-user-scopes: true